---
title: 叶夕青兮
timezone: UTC
newsletter: "生活就是一本书，一壶茶，一个阳光明媚的下午"
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
production: true
email: zhangshiyu1992@hotmail.com
author: Erl
baseurl: ''
url: https://erl.im
github_username: erlzhang
sass:
  sass_dir: _sass
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- build.sh
- src
- package.json
- package-lock.json
- webpack.config.js
- README.md
pagination:
  enabled: true
  per_page: 5
  indexpage: index
  title: ":title"
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

locales:
  zh:
    index: "/blog"
    blog_title: "博客"
    langs:
      zh: "中文"
      en: "英文"
  en:
    index: "/blog/en"
    blog_title: "Blog"
    langs:
      zh: "Chinese"
      en: "English"
