---
title: 叶夕青兮
newsletter: 生活就是一本书，一壶茶，一个阳光明媚的下午
keywords: 叶夕青兮, 原创独立博客, Erl, Jekyll
description: 叶夕青兮，目前还是程序员。这里是她的独立博客，分享编程、建站、生活感悟、读书随笔、原创小说等。
production: true
email: zhangshiyu1992@hotmail.com
author: Erl
url: http://yexiqingxi.com
github_username: erlzhang
version: v3.4.20190104
sass:
  sass_dir: _sass
markdown: kramdown
permalink: /blog/:title:output_ext
timezone: Asia/Shanghai
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build.sh
  - src
  - package.json
  - package-lock.json
  - webpack.config.js
  - README.md
  - staticman.yml

comment:
  enabled: true
  postUrl: "http://yexiqingxi.com:8979/v2/entry/erlzhang/persephone/master/comments"

pagination:
  enabled: true
  per_page: 5
  indexpage: index
  title: ":title"
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2

locales:
  zh:
    index: "/blog"
    blog_title: "博客"
    langs:
      zh: "中文"
      en: "英文"
  en:
    index: "/blog/en"
    blog_title: "Blog"
    langs:
      zh: "Chinese"
      en: "English"
