---
title: 叶夕青兮
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: zhangshiyu1992@hotmail.com
author: Erl
baseurl: ''
url: http://yexiqingxi.com
github_username: erlzhang
sass:
  sass_dir: _sass
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate-v2
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- build.sh
- src
- package.json
- package-lock.json
- webpack.config.js
- README.md
pagination:
  enabled: true
  per_page: 10
  indexpage: index
  title: ":title"
  sort_field: date
  sort_reverse: true
  trail:
    before: 2
    after: 2
