# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh erl@96.45.183.112 -p 28801 "cd /home/erl/workspace/persephone; git pull; sh build.sh"
