# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
defaults: &defaults
  working_directory: ~/repo
version: 2
jobs:
  <<: *defaults
  deploy:
    machine:
      enabled: true
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: Deploy Over SSH
          command: |
            ssh erl@96.45.183.112 -p 28801 "cd /home/erl/workspace/persephone; git pull; sh build.sh"

workflows:
  version: 2
  desploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
