backend:
  name: git-gateway
media_folder: "img"
site_url: "https://erl.im"
slug:
  sanitize_replacement: "-"
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "文章" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "blog/{{name}}"
    fields: # The fields for each document, usually in front matter
      - {label: "标题", name: "title", widget: "string"}
      - {label: "Slug", name: "name", widget: "string", required: false}
      - {label: "发布日期", name: "date", widget: "datetime", required: false}
      - {label: "代码高亮", name: "code", widget: "boolean", default: false, required: false}
      - {label: "流程图", name: "mermaid", widget: "boolean", default: false, required: false}
      - {label: "公式", name: "math", widget: "boolean", default: false, required: false}
      - {label: "内容", name: "body", widget: "markdown"}

