backend:
  name: github
  repo: erlzhang/persephone # Path to your Github/Gitlab repository
  branch: master    # Branch to update
  base_url: https://erl.im/ # Path to ext auth providera
media_folder: "img"
collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Name", name: "name", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Code", name: "code", widget: "boolean", default: false, required: false}
      - {label: "mermaid", name: "mermaid", widget: "boolean", default: false, required: false}
      - {label: "math", name: "math", widget: "boolean", default: false, required: false}
      - {label: "Body", name: "body", widget: "markdown"}

